default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: icm_development

test:
  <<: *default
  database: icm_test

production:
  <<: *default
  database: icm_production
  username: <%= Rails.application.credentials.database_username %>
  password: <%= Rails.application.credentials.database_password %>
